/*
 * generated by Xtext
 */
package org.bundlemaker.core.transformations.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.validation.ValidatingEditorCallback;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TransformationDslUiModule extends org.bundlemaker.core.transformations.dsl.ui.AbstractTransformationDslUiModule {
	public TransformationDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	 // contributed by org.eclipse.xtext.generator.builder.BuilderIntegrationFragment
  public Class<? extends org.eclipse.xtext.ui.editor.IXtextEditorCallback> bindIXtextEditorCallback2() {
    return ValidatingEditorCallback.class;
  }
}
