/*
 * generated by Xtext
 */
package org.bundlemaker.core.transformations.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TransformationDslUiModule extends org.bundlemaker.core.transformations.dsl.ui.AbstractTransformationDslUiModule {
	public TransformationDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
