/*
 * generated by Xtext
 */
package org.bundlemaker.core.transformations.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TransformationDslRuntimeModule extends org.bundlemaker.core.transformations.dsl.AbstractTransformationDslRuntimeModule {

}
