<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="org"
    nsURI="http://www.bundlemaker.org/org" nsPrefix="org">
  <eSubpackages name="bundlemaker" nsURI="http://www.bundlemaker.org/org/bundlemaker"
      nsPrefix="bundlemaker">
    <eSubpackages name="core" nsURI="http://www.bundlemaker.org/org/bundlemaker/core"
        nsPrefix="core">
      <eSubpackages name="model" nsURI="http://www.bundlemaker.org/org/bundlemaker/core/model"
          nsPrefix="model">
        <eSubpackages name="internal" nsURI="http://www.bundlemaker.org/org/bundlemaker/core/model/internal"
            nsPrefix="internal">
          <eSubpackages name="projectdescription" nsURI="http://www.bundlemaker.org/org/bundlemaker/core/model/internal/projectdescription"
              nsPrefix="projectdescription">
            <eClassifiers xsi:type="ecore:EClass" name="EProjectDescription">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="jre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="fileBasedContent"
                  upperBound="-1" eType="#//bundlemaker/core/model/internal/projectdescription/EFileBasedContent"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="EFileBasedContent">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="binaryPathNames"
                  upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
              <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContent"
                  eType="#//bundlemaker/core/model/internal/projectdescription/EResourceContent"
                  containment="true"/>
            </eClassifiers>
            <eClassifiers xsi:type="ecore:EClass" name="EResourceContent">
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="analyzeSourceResources"
                  eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
              <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourcePathNames"
                  upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
            </eClassifiers>
          </eSubpackages>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
