//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.11 at 08:54:48 PM MESZ 
//


package org.bundlemaker.analysis.xml.internal;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for groupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="groupType">
 *   &lt;complexContent>
 *     &lt;extension base="{}abstractArtifactType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="group" type="{}groupType"/>
 *         &lt;element name="module" type="{}moduleType"/>
 *       &lt;/choice>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "groupType", propOrder = {
    "groupOrModule"
})
public class GroupType
    extends AbstractArtifactType
{

    @XmlElements({
        @XmlElement(name = "module", type = ModuleType.class),
        @XmlElement(name = "group", type = GroupType.class)
    })
    protected List<AbstractArtifactType> groupOrModule;

    /**
     * Gets the value of the groupOrModule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupOrModule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupOrModule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModuleType }
     * {@link GroupType }
     * 
     * 
     */
    public List<AbstractArtifactType> getGroupOrModule() {
        if (groupOrModule == null) {
            groupOrModule = new ArrayList<AbstractArtifactType>();
        }
        return this.groupOrModule;
    }

}
