
/*
 * generated by Xtext
 */
 
package org.bundlemaker.core.transformations.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class TransformationDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.bundlemaker.core.transformations.dsl.ui.internal.TransformationDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.bundlemaker.core.transformations.dsl.ui.internal.TransformationDslActivator.getInstance().getInjector("org.bundlemaker.core.transformations.dsl.TransformationDsl");
	}
	
}
