//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 04:19:30 PM MEZ 
//


package org.bundlemaker.core.model.internal.projectdescription.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContentProviderFactoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContentProviderFactoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;any/>
 *       &lt;/sequence>
 *       &lt;attribute name="contentProviderFactoryClass" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contentProviderFactoryId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContentProviderFactoryType", propOrder = {
    "any"
})
public class ContentProviderFactoryType {

    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(required = true)
    protected String contentProviderFactoryClass;
    @XmlAttribute(required = true)
    protected String contentProviderFactoryId;

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

    /**
     * Gets the value of the contentProviderFactoryClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentProviderFactoryClass() {
        return contentProviderFactoryClass;
    }

    /**
     * Sets the value of the contentProviderFactoryClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentProviderFactoryClass(String value) {
        this.contentProviderFactoryClass = value;
    }

    /**
     * Gets the value of the contentProviderFactoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentProviderFactoryId() {
        return contentProviderFactoryId;
    }

    /**
     * Sets the value of the contentProviderFactoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentProviderFactoryId(String value) {
        this.contentProviderFactoryId = value;
    }

}
