//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.13 at 04:19:36 PM MEZ 
//


package org.bundlemaker.core.content.file.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bundlemaker.core.content.file.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XmlFileBasedContent_QNAME = new QName("", "XmlFileBasedContent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bundlemaker.core.content.file.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlResourceContentType }
     * 
     */
    public XmlResourceContentType createXmlResourceContentType() {
        return new XmlResourceContentType();
    }

    /**
     * Create an instance of {@link XmlFileBasedContentType }
     * 
     */
    public XmlFileBasedContentType createXmlFileBasedContentType() {
        return new XmlFileBasedContentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlFileBasedContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XmlFileBasedContent")
    public JAXBElement<XmlFileBasedContentType> createXmlFileBasedContent(XmlFileBasedContentType value) {
        return new JAXBElement<XmlFileBasedContentType>(_XmlFileBasedContent_QNAME, XmlFileBasedContentType.class, null, value);
    }

}
