/*
* generated by Xtext
*/
package org.bundlemaker.core.transformations.dsl.ui.contentassist;

import org.bundlemaker.core.transformations.dsl.ui.contentassist.AbstractTransformationDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TransformationDslProposalProvider extends AbstractTransformationDslProposalProvider {

}
