//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.26 at 10:30:39 PM MESZ 
//


package org.bundlemaker.core.mvn.content.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bundlemaker.core.mvn.content.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MvnContent_QNAME = new QName("", "mvnContent");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bundlemaker.core.mvn.content.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MvnContentType }
     * 
     */
    public MvnContentType createMvnContentType() {
        return new MvnContentType();
    }

    /**
     * Create an instance of {@link MvnArtifactType }
     * 
     */
    public MvnArtifactType createMvnArtifactType() {
        return new MvnArtifactType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MvnContentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mvnContent")
    public JAXBElement<MvnContentType> createMvnContent(MvnContentType value) {
        return new JAXBElement<MvnContentType>(_MvnContent_QNAME, MvnContentType.class, null, value);
    }

}
