//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.17 at 01:35:18 PM MEZ 
//


package org.bundlemaker.core.model.internal.projectdescription.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlProjectDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlProjectDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fileBasedContent" type="{}XmlFileBasedContentType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="currentId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="jre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlProjectDescriptionType", propOrder = {
    "fileBasedContent"
})
public class XmlProjectDescriptionType {

    protected List<XmlFileBasedContentType> fileBasedContent;
    @XmlAttribute(required = true)
    protected int currentId;
    @XmlAttribute(required = true)
    protected String jre;

    /**
     * Gets the value of the fileBasedContent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileBasedContent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileBasedContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlFileBasedContentType }
     * 
     * 
     */
    public List<XmlFileBasedContentType> getFileBasedContent() {
        if (fileBasedContent == null) {
            fileBasedContent = new ArrayList<XmlFileBasedContentType>();
        }
        return this.fileBasedContent;
    }

    /**
     * Gets the value of the currentId property.
     * 
     */
    public int getCurrentId() {
        return currentId;
    }

    /**
     * Sets the value of the currentId property.
     * 
     */
    public void setCurrentId(int value) {
        this.currentId = value;
    }

    /**
     * Gets the value of the jre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJre() {
        return jre;
    }

    /**
     * Sets the value of the jre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJre(String value) {
        this.jre = value;
    }

}
